AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for Jurassic Park Incident Tracker EKS Cluster
Resources:
  EKSCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: jurassic-eks-cluster
      Version: '1.29' # Compatible avec EKS Auto Mode
      RoleArn: !GetAtt EKSClusterRole.Arn
      ResourcesVpcConfig:
        SubnetIds:
          - subnet-xxxxxxxxxxxxxxxxx
          - subnet-xxxxxxxxxxxxxxxxx
        SecurityGroupIds:
          - sg-xxxxxxxxxxxxxxxxx
  EKSClusterRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: eks.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
  NodeGroup:
    Type: AWS::EKS::Nodegroup
    Properties:
      ClusterName: !Ref EKSCluster
      NodegroupName: jurassic-nodegroup
      ScalingConfig:
        MinSize: 2
        MaxSize: 5
        DesiredSize: 3
      InstanceTypes:
        - t3.medium
      Subnets:
        - subnet-xxxxxxxxxxxxxxxxx
        - subnet-xxxxxxxxxxxxxxxxx
      NodeRole: !GetAtt NodeRole.Arn
  NodeRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: ec2.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
Outputs:
  ClusterEndpoint:
    Value: !GetAtt EKSCluster.Endpoint
  ClusterName:
    Value: !Ref EKSCluster