AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for Jurassic Park Incident Tracker S3 Bucket
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: jurassic-park-static-assets
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            AWS: !GetAtt FrontendIAMRole.Arn
          Action:
            - s3:GetObject
            - s3:PutObject
          Resource: !Sub arn:aws:s3:::jurassic-park-static-assets/*
  FrontendIAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: ec2.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
Outputs:
  BucketName:
    Value: !Ref S3Bucket